CREATE DATABASE ORDER_STORES_DATA

CREATE TABLE ORDER_TABLE
(
ORDER_ID INT ,
ORDER_DATE DATE,
REGION CHAR (50),
REP CHAR (50),
ORDER_ITEAM CHAR (50),
UNITS INT,
UNIT_COST INT,
TOTAL_PRICE INT,
)
 
SELECT * FROM ORDER_TABLE

INSERT INTO ORDER_TABLE (ORDER_ID,ORDER_DATE,REGION,REP,ORDER_ITEAM,UNITS,UNIT_COST,TOTAL_PRICE)
VALUES (1,'1-6-21','EAST','ARUNA','PENCIL',95,1.99,189.05)

INSERT INTO ORDER_TABLE (ORDER_ID,ORDER_DATE,REGION,REP,ORDER_ITEAM,UNITS,UNIT_COST,TOTAL_PRICE)
VALUES (2,'1-23-21','CENTRAL','KIVEll','',50,19.99,999.50)

INSERT INTO ORDER_TABLE (ORDER_ID,ORDER_DATE,REGION,REP,ORDER_ITEAM,UNITS,UNIT_COST,TOTAL_PRICE)
VALUES (3,'2-9-21','CENTRAL','GANESH','',36,4.99,179.64)

INSERT INTO ORDER_TABLE (ORDER_ID,ORDER_DATE,REGION,REP,ORDER_ITEAM,UNITS,UNIT_COST,TOTAL_PRICE)
VALUES (4,'2-26-21','CENTRAL','PAYAL','',27,19.99,539.73)

INSERT INTO ORDER_TABLE (ORDER_ID,ORDER_DATE,REGION,REP,ORDER_ITEAM,UNITS,UNIT_COST,TOTAL_PRICE)
VALUES (5,'3-15-21','WEST','SORVINO','',56,2.99,167.44)
 
INSERT INTO ORDER_TABLE (ORDER_ID,ORDER_DATE,REGION,REP,ORDER_ITEAM,UNITS,UNIT_COST,TOTAL_PRICE)
VALUES (6,'4-1-21','EAST','HITESH','PENCIL',60,4.99,299.40)

INSERT INTO ORDER_TABLE (ORDER_ID,ORDER_DATE,REGION,REP,ORDER_ITEAM,UNITS,UNIT_COST,TOTAL_PRICE)
VALUES (7,'4-18-21','CENTRAL','AKSHITA','',75,1.99,149.25)

INSERT INTO ORDER_TABLE (ORDER_ID,ORDER_DATE,REGION,REP,ORDER_ITEAM,UNITS,UNIT_COST,TOTAL_PRICE)
VALUES (8,'5-5-21','CENTRAL','RUCHIKA','BOOKS',90,4.99,449.10)

INSERT INTO ORDER_TABLE (ORDER_ID,ORDER_DATE,REGION,REP,ORDER_ITEAM,UNITS,UNIT_COST,TOTAL_PRICE)
VALUES (9,'5-22-21','WEST','SURBHI','',32,1.99,63.68)

INSERT INTO ORDER_TABLE (ORDER_ID,ORDER_DATE,REGION,REP,ORDER_ITEAM,UNITS,UNIT_COST,TOTAL_PRICE)
VALUES (10,'6-8-21','EAST','JONES','SUITCASE',60,8.99,539.40)

SELECT * FROM ORDER_TABLE


CREATE TABLE STORES_TABLE
(
STORE_ID INT,
STORE_TYPE CHAR(50),
ASSORTMENT INT,
COMPETITIONDISTANCE INT,
MONTH INT ,
YEAR INT,
PROMOLNTERVAl CHAR (50),
)

SELECT * FROM STORES_TABLE

INSERT INTO STORES_TABLE (STORE_ID,STORE_TYPE,ASSORTMENT,COMPETITIONDISTANCE,MONTH,YEAR,PROMOLNTERVAl)
VALUES (1,'C',19,1270,9,2008,'JAN')

INSERT INTO STORES_TABLE (STORE_ID,STORE_TYPE,ASSORTMENT,COMPETITIONDISTANCE,MONTH,YEAR,PROMOLNTERVAl)
VALUES (2,'A',42,570,11,2007,'FEB')

INSERT INTO STORES_TABLE (STORE_ID,STORE_TYPE,ASSORTMENT,COMPETITIONDISTANCE,MONTH,YEAR,PROMOLNTERVAl)
VALUES (3,'A',19,14130,12,2006,'MAR')

INSERT INTO STORES_TABLE (STORE_ID,STORE_TYPE,ASSORTMENT,COMPETITIONDISTANCE,MONTH,YEAR,PROMOLNTERVAl)
VALUES (4,'C',13,620,9,2009,'')

INSERT INTO STORES_TABLE (STORE_ID,STORE_TYPE,ASSORTMENT,COMPETITIONDISTANCE,MONTH,YEAR,PROMOLNTERVAl)
VALUES (5,'A',38,29910,4,2015,'MAY')

INSERT INTO STORES_TABLE (STORE_ID,STORE_TYPE,ASSORTMENT,COMPETITIONDISTANCE,MONTH,YEAR,PROMOLNTERVAl)
VALUES (6,'A',29,310,12,2013,'JUNE')

INSERT INTO STORES_TABLE (STORE_ID,STORE_TYPE,ASSORTMENT,COMPETITIONDISTANCE,MONTH,YEAR,PROMOLNTERVAl)
VALUES (7,'A',32,24000,4,2013,'')

INSERT INTO STORES_TABLE (STORE_ID,STORE_TYPE,ASSORTMENT,COMPETITIONDISTANCE,MONTH,YEAR,PROMOLNTERVAl)
VALUES (8,'A',13,7520,10,2014,'AUG')

INSERT INTO STORES_TABLE (STORE_ID,STORE_TYPE,ASSORTMENT,COMPETITIONDISTANCE,MONTH,YEAR,PROMOLNTERVAl)
VALUES (9,'A',27,2030,8,2000,'')

INSERT INTO STORES_TABLE (STORE_ID,STORE_TYPE,ASSORTMENT,COMPETITIONDISTANCE,MONTH,YEAR,PROMOLNTERVAl)
VALUES (10,'A',10,3160,9,2009,'OCT')

SELECT * FROM ORDER_TABLE
SELECT * FROM STORES_TABLE

............................................................................

ALTER TABLE STORES_TABLE
ADD STORES_NAME CHAR (50)
SELECT * FROM STORES_TABLE

UPDATE STORES_TABLE
SET STORES_NAME = 'CARS'
WHERE STORE_ID = 1

UPDATE STORES_TABLE
SET STORES_NAME = 'BIKES'
WHERE STORE_ID = 2

UPDATE STORES_TABLE
SET STORES_NAME = 'HARDWARE'
WHERE STORE_ID = 3

UPDATE STORES_TABLE
SET STORES_NAME = 'ELECTRIES'
WHERE STORE_ID = 4

UPDATE STORES_TABLE
SET STORES_NAME = 'FIBERS'
WHERE STORE_ID = 5

UPDATE STORES_TABLE
SET STORES_NAME = 'ELASTICS'
WHERE STORE_ID = 6

UPDATE STORES_TABLE
SET STORES_NAME = 'BOOKS'
WHERE STORE_ID = 7

UPDATE STORES_TABLE
SET STORES_NAME = 'SHOES'
WHERE STORE_ID = 8

UPDATE STORES_TABLE
SET STORES_NAME = 'CLOTHS'
WHERE STORE_ID = 9

UPDATE STORES_TABLE
SET STORES_NAME = 'SCRAPS'
WHERE STORE_ID = 10

SELECT * FROM STORES_TABLE

........................................................................

UPDATE ORDER_TABLE
SET ORDER_ITEAM = 'COMPASS'
WHERE ORDER_ID = 3

UPDATE ORDER_TABLE
SET ORDER_ITEAM = 'TORCH'
WHERE ORDER_ID = 4

UPDATE ORDER_TABLE
SET ORDER_ITEAM = 'PHONE'
WHERE ORDER_ID = 5

UPDATE ORDER_TABLE
SET ORDER_ITEAM = 'LAPTOP'
WHERE ORDER_ID = 7

UPDATE ORDER_TABLE
SET ORDER_ITEAM = 'BOX'
WHERE ORDER_ID = 9

SELECT * FROM ORDER_TABLE

......................................................................

UPDATE STORES_TABLE
SET PROMOLNTERVAl = 'APR'
WHERE STORE_ID = 4

UPDATE STORES_TABLE
SET PROMOLNTERVAl = 'JUL'
WHERE STORE_ID = 7

UPDATE STORES_TABLE
SET PROMOLNTERVAl = 'SEP'
WHERE STORE_ID = 9

SELECT * FROM STORES_TABLE

.....................................................................

EXEC SP_RENAME 'STORES_TABLE.ASSORTMENT ' , 'STORE_NOS';
SELECT * FROM STORES_TABLE
.....................................................................

EXEC SP_RENAME 'ORDER_TABLE.ORDER_ITEAM ' , 'ITEAM_NAME';

.....................................................................
EXEC SP_RENAME 'ORDER_TABLE.REP ' , 'CUSTOMERS_NAME';

SELECT * FROM ORDER_TABLE
.........................................................
SELECT * FROM ORDER_TABLE
ORDER BY
UNIT_COST DESC
.........................................................

EXEC SP_RENAME 'ORDER_TABLE.CUSTOMERS_NAME' , 'CUS_NAME';
SELECT * FROM ORDER_TABLE

SELECT REGION, COUNT(CUS_NAME) AS NUM_CUSTOMERS
FROM ORDER_TABLE
GROUP BY REGION
.........................................................

SELECT SUM(TOTAL_PRICE) AS TOTALPRICE
FROM ORDER_TABLE

SELECT SUM(UNIT_COST) AS TOTALCOST
FROM ORDER_TABLE

.........................................................

SELECT ORDER_DATE, UNIT_COST, STORE_TYPE,YEAR  
FROM ORDER_TABLE 
JOIN
STORES_TABLE 
ON
ORDER_TABLE.ORDER_ID = STORES_TABLE.STORE_ID
.........................................................
 
SELECT ITEAM_NAME
FROM ORDER_TABLE
WHERE ORDER_ID IN ( 4,5,6,9)

.........................................................

SELECT YEAR
FROM STORES_TABLE
WHERE COMPETITIONDISTANCE IN (29910,310,3160)

.........................................................

SELECT ITEAM_NAME
FROM ORDER_TABLE
WHERE TOTAL_PRICE > 200

SELECT ITEAM_NAME
FROM ORDER_TABLE
WHERE TOTAL_PRICE < 400

...........................................................

EXEC SP_RENAME 'STORES_TABLE.COMPETITIONDISTANCE ' , 'CD';
SELECT * FROM STORES_TABLE
...........................................................

SELECT COUNT(STORE_TYPE) AS TOTAl_STORE_TYPE
FROM STORES_TABLE

SELECT COUNT(CD) AS TOTAL_CD
FROM STORES_TABLE

............................................................ 

SELECT * FROM ORDER_TABLE
CROSS JOIN 
STORES_TABLE

..............................................................

DROP DATABASE ORDER_STORES_DATA

...............................................................